"""Audit whether 3D gaze labels can be projected back to screen points.

This is a no-training diagnostic. It checks the mathematical contract behind
the 3D route:

    eye crops -> 3D gaze/ray -> screen intersection -> screen point

The script intentionally separates camera-space gaze, approximate head-space
rotation, ray origin, and screen plane assumptions. It should be run before any
head-local relabeling or 3D retraining.

Usage:
    conda run --no-capture-output -n gaze-env python scripts/analyze_3d_geometry_contract.py \
        --processed-dir dataset_processed \
        --output tmp/geometry_contract.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from data.preprocessing import DEFAULT_GEOMETRY, ScreenCameraGeometry, compute_gaze_vector
from geometry.ray_plane import ray_plane_intersect


def euler_to_rotation_matrix(yaw_deg: float, pitch_deg: float, roll_deg: float) -> np.ndarray:
    """Approximate yaw/pitch/roll rotation matrix using ZYX composition."""
    yaw = np.deg2rad(yaw_deg)
    pitch = np.deg2rad(pitch_deg)
    roll = np.deg2rad(roll_deg)
    cy, sy = np.cos(yaw), np.sin(yaw)
    cp, sp = np.cos(pitch), np.sin(pitch)
    cr, sr = np.cos(roll), np.sin(roll)

    ry = np.array([[cy, 0.0, sy], [0.0, 1.0, 0.0], [-sy, 0.0, cy]], dtype=np.float64)
    rx = np.array([[1.0, 0.0, 0.0], [0.0, cp, -sp], [0.0, sp, cp]], dtype=np.float64)
    rz = np.array([[cr, -sr, 0.0], [sr, cr, 0.0], [0.0, 0.0, 1.0]], dtype=np.float64)
    return rz @ ry @ rx


def screen_plane(
    geometry: ScreenCameraGeometry = DEFAULT_GEOMETRY,
    distance_mm: float | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    dist = geometry.screen_distance_mm if distance_mm is None else distance_mm
    origin = np.array([-geometry.screen_w_mm / 2.0, geometry.cam_above_screen_mm, dist], dtype=np.float64)
    normal = np.array([0.0, 0.0, 1.0], dtype=np.float64)
    x_axis = np.array([1.0, 0.0, 0.0], dtype=np.float64)
    y_axis = np.array([0.0, 1.0, 0.0], dtype=np.float64)
    return origin, normal, x_axis, y_axis


def project_gaze_to_norm(
    gaze: np.ndarray,
    ray_origin: np.ndarray | None = None,
    geometry: ScreenCameraGeometry = DEFAULT_GEOMETRY,
    distance_mm: float | None = None,
) -> tuple[float, float] | None:
    origin, normal, x_axis, y_axis = screen_plane(geometry, distance_mm)
    ray_origin = np.zeros(3, dtype=np.float64) if ray_origin is None else np.asarray(ray_origin, dtype=np.float64)
    direction = np.asarray(gaze, dtype=np.float64).reshape(3)
    norm = np.linalg.norm(direction)
    if norm < 1e-10:
        return None
    direction = direction / norm
    hit = ray_plane_intersect(ray_origin, direction, origin, normal)
    if hit is None:
        return None
    local = hit - origin
    x_mm = float(np.dot(local, x_axis))
    y_mm = float(np.dot(local, y_axis))
    return x_mm / geometry.screen_w_mm, y_mm / geometry.screen_h_mm


def implied_screen_distance_mm(
    gaze: np.ndarray,
    norm_target: np.ndarray,
    geometry: ScreenCameraGeometry = DEFAULT_GEOMETRY,
    epsilon: float = 1e-6,
) -> float:
    """Estimate the screen Z distance implied by one gaze label and target.

    A camera-space label generated by this project points from origin to:
        [target_x_mm, target_y_mm, screen_distance_mm].
    If the stored gaze and target are consistent, x/gx and y/gy imply the
    original ray scale, and scale * gz gives the per-row screen distance.
    """
    direction = np.asarray(gaze, dtype=np.float64).reshape(3)
    norm = np.linalg.norm(direction)
    if norm < 1e-10 or abs(direction[2]) < epsilon:
        return float("nan")
    direction = direction / norm
    nx, ny = np.asarray(norm_target, dtype=np.float64).reshape(2)
    target_x_mm = nx * geometry.screen_w_mm - geometry.screen_w_mm / 2.0
    target_y_mm = geometry.cam_above_screen_mm + ny * geometry.screen_h_mm

    scales = []
    if abs(direction[0]) > epsilon and abs(target_x_mm) > epsilon:
        scales.append(target_x_mm / direction[0])
    if abs(direction[1]) > epsilon and abs(target_y_mm) > epsilon:
        scales.append(target_y_mm / direction[1])
    if not scales:
        return float("nan")
    return float(np.median(scales) * direction[2])


def projection_metrics(
    predicted_norm: np.ndarray,
    target_norm: np.ndarray,
    screen_w: int = 1920,
    screen_h: int = 1080,
) -> dict[str, float]:
    valid = np.isfinite(predicted_norm).all(axis=1)
    if not np.any(valid):
        return {"valid_ratio": 0.0}
    pred = predicted_norm[valid]
    target = target_norm[valid]
    diff = pred - target
    px = diff[:, 0] * screen_w
    py = diff[:, 1] * screen_h
    pixel = np.sqrt(px * px + py * py)
    in_screen = (
        (pred[:, 0] >= 0.0)
        & (pred[:, 0] <= 1.0)
        & (pred[:, 1] >= 0.0)
        & (pred[:, 1] <= 1.0)
    )
    return {
        "valid_ratio": float(np.mean(valid)),
        "in_screen_ratio": float(np.mean(in_screen)),
        "mean_pixel_error": float(np.mean(pixel)),
        "median_pixel_error": float(np.median(pixel)),
        "p95_pixel_error": float(np.quantile(pixel, 0.95)),
        "mean_norm_error": float(np.mean(np.linalg.norm(diff, axis=1))),
    }


def describe(values: pd.Series | np.ndarray) -> dict[str, float]:
    arr = pd.to_numeric(pd.Series(values), errors="coerce").dropna().to_numpy(dtype=np.float64)
    if arr.size == 0:
        return {"count": 0}
    return {
        "count": int(arr.size),
        "mean": float(np.mean(arr)),
        "std": float(np.std(arr)),
        "min": float(np.min(arr)),
        "p50": float(np.median(arr)),
        "max": float(np.max(arr)),
    }


def load_processed(processed_dir: Path, split: str) -> pd.DataFrame:
    labels_path = processed_dir / split / "labels.csv"
    if not labels_path.exists():
        raise FileNotFoundError(labels_path)
    return pd.read_csv(labels_path)


def analyze_processed_geometry(df: pd.DataFrame) -> dict[str, object]:
    gaze = df[["gaze_x", "gaze_y", "gaze_z"]].to_numpy(dtype=np.float64)
    target = df[["norm_target_x", "norm_target_y"]].to_numpy(dtype=np.float64)
    yaw = pd.to_numeric(df.get("head_yaw", 0.0), errors="coerce").fillna(0.0).to_numpy(dtype=np.float64)
    pitch = pd.to_numeric(df.get("head_pitch", 0.0), errors="coerce").fillna(0.0).to_numpy(dtype=np.float64)
    roll = pd.to_numeric(df.get("head_roll", 0.0), errors="coerce").fillna(0.0).to_numpy(dtype=np.float64)

    variants: dict[str, list[tuple[float, float] | None]] = {
        "camera_space_zero_origin": [],
        "camera_space_implied_screen_distance": [],
        "camera_space_face_translation_z500": [],
        "approx_head_rotation_applied": [],
        "approx_inverse_head_local_projected": [],
        "z_flipped_camera_space": [],
    }
    local_z = []
    rotated_z = []
    implied_distances = []
    for vec, tgt, y, p, r in zip(gaze, target, yaw, pitch, roll):
        R = euler_to_rotation_matrix(y, p, r)
        local = R.T @ vec
        rotated = R @ vec
        implied_dist = implied_screen_distance_mm(vec, tgt)
        implied_distances.append(implied_dist)
        local_z.append(local[2])
        rotated_z.append(rotated[2])
        variants["camera_space_zero_origin"].append(project_gaze_to_norm(vec))
        variants["camera_space_implied_screen_distance"].append(
            project_gaze_to_norm(vec, distance_mm=implied_dist)
            if np.isfinite(implied_dist) and implied_dist > 0
            else None
        )
        variants["camera_space_face_translation_z500"].append(
            project_gaze_to_norm(vec, ray_origin=np.array([0.0, 0.0, 500.0], dtype=np.float64))
        )
        variants["approx_head_rotation_applied"].append(project_gaze_to_norm(rotated))
        variants["approx_inverse_head_local_projected"].append(project_gaze_to_norm(local))
        variants["z_flipped_camera_space"].append(project_gaze_to_norm(np.array([vec[0], vec[1], -vec[2]])))

    metrics = {}
    for name, values in variants.items():
        arr = np.array(
            [[np.nan, np.nan] if v is None else [float(v[0]), float(v[1])] for v in values],
            dtype=np.float64,
        )
        metrics[name] = projection_metrics(arr, target)

    return {
        "rows": int(len(df)),
        "pose": {
            "head_yaw": describe(yaw),
            "head_pitch": describe(pitch),
            "head_roll": describe(roll),
            "abs_gt_90_ratio": {
                "head_yaw": float(np.mean(np.abs(yaw) > 90.0)),
                "head_pitch": float(np.mean(np.abs(pitch) > 90.0)),
                "head_roll": float(np.mean(np.abs(roll) > 90.0)),
            },
        },
        "gaze_z": describe(gaze[:, 2]),
        "implied_screen_distance_mm": describe(np.asarray(implied_distances)),
        "approx_inverse_local_z": describe(np.asarray(local_z)),
        "approx_inverse_local_z_negative_ratio": float(np.mean(np.asarray(local_z) < 0.0)),
        "approx_rotated_z": describe(np.asarray(rotated_z)),
        "projection_variants": metrics,
    }


def synthetic_projection_check() -> dict[str, object]:
    targets = [(0.1, 0.1), (0.5, 0.5), (0.9, 0.9)]
    errors = []
    for nx, ny in targets:
        gx, gy, gz = compute_gaze_vector(nx * 1920, ny * 1080, 1920, 1080)
        projected = project_gaze_to_norm(np.array([gx, gy, gz], dtype=np.float64))
        if projected is None:
            errors.append(float("inf"))
        else:
            errors.append(float(np.linalg.norm(np.array(projected) - np.array([nx, ny]))))
    return {
        "max_norm_error": float(np.max(errors)),
        "passes": bool(np.max(errors) < 1e-9),
    }


def print_summary(summary: dict[str, object]) -> None:
    print(f"[3d-contract] synthetic_projection_passes={summary['synthetic_projection']['passes']}")
    processed = summary.get("processed", {})
    print(f"[3d-contract] rows={processed.get('rows')}")
    pose = processed.get("pose", {})
    if pose:
        print(f"[3d-contract] pose_abs_gt_90={pose.get('abs_gt_90_ratio')}")
    print(
        "[3d-contract] inverse_local_z_negative_ratio="
        f"{processed.get('approx_inverse_local_z_negative_ratio')}"
    )
    variants = processed.get("projection_variants", {})
    for name, metrics in variants.items():
        print(
            "[3d-contract] "
            f"{name}: valid={metrics.get('valid_ratio', 0):.3f} "
            f"in_screen={metrics.get('in_screen_ratio', 0):.3f} "
            f"mean_px={metrics.get('mean_pixel_error', 0):.1f} "
            f"p95_px={metrics.get('p95_pixel_error', 0):.1f}"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit 3D gaze-to-screen geometry contract")
    parser.add_argument("--processed-dir", default="dataset_processed")
    parser.add_argument("--split", default="test")
    parser.add_argument("--output", default=None)
    args = parser.parse_args()

    summary = {"synthetic_projection": synthetic_projection_check()}
    df = load_processed(Path(args.processed_dir), args.split)
    summary["processed"] = analyze_processed_geometry(df)
    print_summary(summary)
    if args.output:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
